### ISSUE TITLE
Doesn't run on hardware

### ISSUE THREAD

**Issue by basxto** [mattcurrie/cgb-acid-hell#1]
This doesn’t work on my 
cgb d
cgb-cpu-05
c/cgb-eur

![IMG_20210320_202305](https://user-images.githubusercontent.com/1314450/111883277-8dbf9f00-89ba-11eb-9d24-3dac15fd8c2e.jpg)

**Comment by mattcurrie** [comment]
Yes, that is the intended behaviour. 

Devices with CPU CGB D revision SoC don't get to play 😛

**Comment by basxto** [comment]
Maybe change the
> An accurate emulator should generate output identical to the image below:

part then. Since they could be accurate and not have an identical image if they decide to emulate CGB D

**Comment by mattcurrie** [comment]
It goes against the spirit of this test to be too helpful, but maybe I can tweak that text a bit 😁
